layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: danielz02
  # hackerrank: your_username
  instagram: danielz233
  # keybase: your_username
  linkedin: danielz02
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: danielz233
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://danielz.ch
  # youtube: your_username
  wechat: https://imgur.com/a/mTW86Ya

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/izumin5210/emojipack-for-devicon/master/png/java.png

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/izumin5210/emojipack-for-devicon/master/png/android.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/izumin5210/emojipack-for-devicon/master/png/python.png

  - name: Kotlin
    web_url: https://github.com/topics/kotlin
    image_url: https://upload.wikimedia.org/wikipedia/commons/b/b5/Kotlin-logo.png

  - name: PyTorch
    web_url: https://pytorch.org/
    image_url: https://static.nvidiagrid.net/ngc/containers/pytorch-logo-light.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: assets/Typescript.png


